language: go
sudo: false
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
install:
  # Imagemagick
  - sh -c "
    export IMAGEMAGICK_VERSION=6.9.6-8
    wget http://www.imagemagick.org/download/legacy/ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
    tar xzf ImageMagick-${IMAGEMAGICK_VERSION}.tar.gz
    cd ImageMagick-${IMAGEMAGICK_VERSION}
    ./configure --prefix=/opt/imagemagick
    make -j
    sudo make install
    "
  # glide
  - go get github.com/Masterminds/glide
  - glide install
  # enable vendering
  - export GO15VENDOREXPERIMENT=1
script:
  - cd thumbnail && go build .
  - cd thumberd  && go build .
